version: '3'

services:
  proxy:
    image: zzci/proxy
    container_name: proxy
    hostname: 'proxy'
    volumes:
      - ./work:/work
    networks:
      - proxy

networks:
  proxy:
    external:
      name: proxy

